## Библиотека NumPy

Библиотека предназаченная для работы с массивами. Почему не встроенные массивы?

In [3]:
import numpy as np

In [5]:
%timeit [i**2 for i in range(1000)]

203 µs ± 5.32 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit np.arange(1000)**2

1.24 µs ± 8.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Создадим простой массив с помощью numpy

In [7]:
a = np.array([1,3,4,5])
a

array([1, 3, 4, 5])

In [15]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [16]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a.ndim

2

In [18]:
a.shape

(3, 2)

смотрим размерность массива

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [14]:
len(a) == a.shape[0]

True

In [11]:
b = np.array([[(1,2),(3,4)],[(1,2),(3,4)]] )
print(b.ndim)
print(b.shape)
print(b)

3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [12]:
# при этом длинна массива будет все равно 2
len(b)

2

### Создание массивов

**На практике мы редко добавляем элементы по одному и нужно создавать матрицу/массив нужной размерности**

- Равномерно распределенные элементы:

In [67]:
a = np.arange(10) # 0 .. n-1  (!)
a.dtype

dtype('int64')

In [ ]:
b = np.arange(1, 11, 2) # начало, конец(не включая), шаг
b

array([1, 3, 5, 7, 9])

- по числу элементов:

In [66]:
c = np.linspace(0, 1, 6)   # начало, конец, количество точек
c.dtype

dtype('float64')

In [65]:
d = np.linspace(0, 1, 5, endpoint=False)
d.dtype

dtype('float64')

- Часто встречающиеся массивы:

In [64]:
a = np.ones(10)
a.dtype

dtype('float64')

In [63]:
b = np.zeros((2, 2, 2))
b.dtype

dtype('float64')

In [62]:
c = np.eye(5)
c.dtype

dtype('float64')

In [68]:
d = np.diag(np.arange(1, 5))
d.dtype

dtype('int64')

* `np.random` генерация случайных чисел:

In [61]:
a = np.random.rand(3,3) # [0, 1)
a.dtype

dtype('float64')

In [52]:
# np.random.seed(42)
b = np.random.randn(10, 3)
b  

array([[ 0.63630511, -0.90672067,  0.47604259],
       [ 1.30366127,  0.21158701,  0.59704465],
       [-0.89633518, -0.11198782,  1.46894129],
       [-1.12389833,  0.9500054 ,  1.72651647],
       [ 0.45788508, -1.68428738,  0.32684522],
       [-0.08111895,  0.46779475,  0.73612235],
       [-0.77970188, -0.84389636, -0.15053386],
       [-0.96555767,  0.15048908, -0.11342125],
       [ 2.63352822, -1.02509089, -0.78204783],
       [ 0.42394307,  0.8727051 ,  2.28722598]])

In [54]:
np.random.randint(0, 5, (10, 3))

array([[4, 3, 4],
       [2, 2, 3],
       [1, 1, 4],
       [0, 4, 3],
       [3, 3, 3],
       [3, 2, 1],
       [3, 0, 0],
       [0, 0, 2],
       [0, 3, 4],
       [0, 2, 2]])

### Основные типы данных NumPy

In [ ]:
import numpy as np

In [70]:
np.array([True, False, False]).dtype

dtype('bool')

In [58]:
a = np.array([1, 2, 3, 0.5])
a.dtype

dtype('float64')

Точка после числа означает, что это тип данных `float64`

In [60]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [ ]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

Прочие типы данных:

- Комплексные числа

In [72]:
d = np.array([1+2j, 3+4j, 5+6j])
d.dtype

dtype('complex128')

 - Bool

In [73]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

### Индексирование массивов и срезы

В целом так же, как со встроенными последовательностями Python (например, как со списками).

**Индексирование**

In [74]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a[0], a[2], a[-1]

(0, 2, 9)

Работает и популярный в Python способ отражения массива:

In [76]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Для многомерных массивов индексы - это кортежи целых чисел. Кортеж, по сути - неизменяемый список.

In [77]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [79]:
%timeit a[1, 1]

62.9 ns ± 1.47 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [80]:
%timeit a[1][1]

108 ns ± 1.56 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [81]:
a[2, 1] = 10 
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [ ]:
a[1]

array([0, 1, 0])

**Срезы**

In [82]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a[1::2] # [начало:конец:шаг]

array([1, 3, 5, 7, 9])

Последний индекс не включается

In [84]:
a[:4]

array([0, 1, 2, 3])

Можно совмещать присваивание и срез:

In [85]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [86]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [93]:
np.random.seed(37)
a = np.random.randint(0, 20, 15)
a

array([15, 11, 12,  3,  3, 10,  8,  8,  3, 18, 12, 14, 12, 17, 19])

In [ ]:
(a % 3 == 0)

array([ True, False,  True,  True,  True, False, False, False,  True,
        True,  True, False,  True, False, False])

In [88]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [89]:
a % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [90]:
a[a % 3 == 0]

array([0, 3, 3, 0])

In [91]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [92]:
mask = (a % 3 == 0)
extract_from_a = a[mask] 
extract_from_a           

array([0, 3, 3, 0])

Индексирование маской может быть очень полезным для присваивания значений части элементов массива:

In [94]:
a

array([15, 11, 12,  3,  3, 10,  8,  8,  3, 18, 12, 14, 12, 17, 19])

In [95]:
a[a % 3 == 0] = -1
a

array([-1, 11, -1, -1, -1, 10,  8,  8, -1, -1, -1, 14, -1, 17, 19])

Индексирование массивом целых чисел

In [96]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
a[[2, 3, 2, 4, 2]]  # тут должен быть питоновский лист

array([20, 30, 20, 40, 20])

In [98]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [99]:
a = np.arange(2, 12)
idx = np.array([[3, 4], [9, 7]])
idx.shape

(2, 2)

In [100]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
idx

array([[3, 4],
       [9, 7]])

In [102]:
a[idx]

array([[ 5,  6],
       [11,  9]])

### Умножение матриц и столбцов

In [104]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)
r3 = a @ b

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат умножения функцией:\n", r1)
print("Результат умножения методом:\n", r2)
print("Результат умножения методом:\n", r3)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]


Матрицы в `NumPy` можно умножать и на векторы:

In [106]:
c = np.array([1, 2])
r1 = np.dot(b, c)
r2 = b.dot(c)
r3 = b @ c

print("Матрица:\n", b)
print("Вектор:\n", c)
print("Результат умножения функцией:\n", r1)
print("Результат умножения методом:\n", r2)
print("Результат умножения методом:\n", r3)

Матрица:
 [[4 1]
 [2 2]]
Вектор:
 [1 2]
Результат умножения функцией:
 [6 6]
Результат умножения методом:
 [6 6]
Результат умножения методом:
 [6 6]


__Обратите внимание:__ операция __`*`__ производит над матрицами покоординатное умножение, а не матричное!

In [112]:
r = a * b

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат покоординатного умножения через операцию *:\n", r)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат покоординатного умножения через операцию *:
 [[4 0]
 [0 2]]


In [123]:
"234".isnumeric()

True

In [132]:
a = input().split()
if a[-1].isnumeric():
    dtype = 'float64'
    shape = list(map(int, a))
else:
    dtype = a[-1]
    shape = list(map(int, a[:-1]))
np.zeros(shape, dtype=dtype)

3 3


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [131]:
np.zeros((3,3), dtype="bool")

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [136]:
np.arange(10, 20).reshape((2, 5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [128]:
np.zeros(5).dtype

dtype('float64')

In [125]:
dtype

'bool'

In [126]:
shape

[2, 3]

In [113]:
a.min()

0

In [114]:
a.max()

1

In [115]:
a

array([[1, 0],
       [0, 1]])

In [116]:
b

array([[4, 1],
       [2, 2]])

In [117]:
b.sum(axis=1)

array([5, 4])

Более подробно о матричном умножении в `NumPy`
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

In [ ]:
a = np.array([1,2,3])
a.cumsum()

array([1, 3, 6], dtype=int32)

In [ ]:
a.min()

1

In [ ]:
a.max()

3